version: '3.8'
services:
  app:
    image: otel-native-graalvm
    environment:
      OTEL_SERVICE_NAME: "graal-native-example-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
    ports:
      - "8080:8080"
    depends_on:
      - collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.158.0@sha256:c5918f78992ee73b0d6f0e599423ac5ec52dd5d9726733114d6eca53d5a32ed5
    volumes:
      - ./collector-spring-native-config.yaml:/collector-spring-native-config.yaml
    command: ["--config=/collector-spring-native-config.yaml"]
    expose:
      - "4317"
    ports:
      - "4317:4317"
