version: '3.8'
services:
  app:
    image: otel-native-graalvm
    environment:
      OTEL_SERVICE_NAME: "graal-native-example-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
    ports:
      - "8080:8080"
    depends_on:
      - collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.150.1@sha256:a516c26968aa1feb5e5fc0562e3338ea13755cb4f373603226bcc4e276374ad0
    volumes:
      - ./collector-spring-native-config.yaml:/collector-spring-native-config.yaml
    command: ["--config=/collector-spring-native-config.yaml"]
    expose:
      - "4317"
    ports:
      - "4317:4317"
