version: '3.8'
services:
  app:
    image: otel-native-graalvm
    environment:
      OTEL_SERVICE_NAME: "graal-native-example-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
    ports:
      - "8080:8080"
    depends_on:
      - collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.159.0@sha256:1f2c54a30e713fac6b3ae77a1ec84010c2007e29ced8ec666214fc2f6739c1cc
    volumes:
      - ./collector-spring-native-config.yaml:/collector-spring-native-config.yaml
    command: ["--config=/collector-spring-native-config.yaml"]
    expose:
      - "4317"
    ports:
      - "4317:4317"
