# Lychee configuration file
# See https://lychee.cli.rs/config/

timeout = 30
retry_wait_time = 5
max_retries = 6
max_concurrency = 4

# Check link anchors
include_fragments = true

exclude = [
  "^http://localhost:",
  "^http://0.0.0.0:",
]
