global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        
  - job_name: 'dice-server'
    static_configs:
      - targets: ['dice-server:8080']
    metrics_path: '/actuator/prometheus'