version: '3'
services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.155.0@sha256:4935caa35e9a4cb387e35732e8fb22b2b5759af8d12e7043357f03837f6e8df5
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    ports:
      - "4317:4317"
