version: '3'
services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.150.1@sha256:a516c26968aa1feb5e5fc0562e3338ea13755cb4f373603226bcc4e276374ad0
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    ports:
      - "4317:4317"
