receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug]
