apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: hello-resource-java
spec:
  template:
    metadata:
      name: hello-resource-java
      labels:
        service: hello-resource-java
    spec:
      containers:
        - name: hello-resource-java
          image: "%REGISTRY_LOCATION%-docker.pkg.dev/%GOOGLE_CLOUD_PROJECT%/%ARTIFACT_REGISTRY%/hello-resource-java:latest"
          env:
            - name: OTEL_TRACES_EXPORTER
              value: none
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONTAINER_NAME
              value: hello-resource-java
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE_NAME),k8s.container.name=$(CONTAINER_NAME)
      # Do not restart containers after they exit
      restartPolicy: Never
  # of retries before marking as failed.
  backoffLimit: 4
