services:
  app:
    build: ./
    ports:
      - '19090:19090'
  prometheus:
    image: prom/prometheus@sha256:efd719c99d83b060d9daefdcf00360461adf279f45ef5391f8d111892118753e
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    ports:
      - '9090:9090'
