services:
  app:
    build: ./
    ports:
      - '19090:19090'
  prometheus:
    image: prom/prometheus@sha256:c6b27ea434f8389bfe233fbc7be381cf50587c286e871bc842008f5a1b1908a7
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    ports:
      - '9090:9090'
