services:
  app:
    build: ./
    ports:
      - '19090:19090'
  prometheus:
    image: prom/prometheus@sha256:759ea6db49103737f2a6f420b0d1632062d8ad99dec086c76db605fd0bf23e15
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    ports:
      - '9090:9090'
