receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317
      http:
        endpoint: "0.0.0.0:4318"
exporters:
  debug:
    verbosity: detailed
  nop:
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
