version: '3'
services:
  app:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "agent-example-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
    ports:
      - "8080:8080"
    depends_on:
      - collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.154.0@sha256:b3079f45e19bdb7326bf49cdddce6cf60dfd865138db39f2733ea48ab17bc4cb
    volumes:
      - ./collector-config.yaml:/collector-config.yaml
    command: ["--config=/collector-config.yaml"]
    expose:
      - "4318"
    ports:
      - "4318:4318"
