apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      filelog/otlp-json-logs:
        include:
          - /var/log/pods/*/*/*.log
        include_file_path: true
        operators:
          - id: container-parser
            type: container
            
    extensions:
      # needed if you use the docker-lgtm image
      health_check:
        endpoint: 0.0.0.0:13133
        path: "/ready"
        
    processors:
      batch:
      resourcedetection:
        detectors: [ "env", "system" ]
        override: false

      k8sattributes:
      # Config details in 
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor
    connectors:
      otlpjson:

    exporters:
      otlphttp/metrics:
        endpoint: http://localhost:9090/api/v1/otlp
      otlphttp/traces:
        endpoint: http://localhost:4418
      otlphttp/logs:
        endpoint: http://localhost:3100/otlp
      debug/metrics:
        verbosity: detailed
      debug/traces:
        verbosity: detailed
      debug/logs:
        verbosity: detailed
      nop:
    
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ k8sattributes, resourcedetection, batch ]
          exporters: [ otlphttp/traces ]
        metrics:
          receivers: [ otlp ]
          processors: [ k8sattributes, resourcedetection, batch ]
          exporters: [ otlphttp/metrics ]
        logs/raw_otlpjson:
          receivers: [ filelog/otlp-json-logs ]
          # No need for processors before the otlpjson connector
          # Declare processors in the shared "logs" pipeline below
          processors: [ ]
          exporters: [ otlpjson ]
        logs/otlp:
          receivers: [ otlp, otlpjson ]
          processors: [ k8sattributes, resourcedetection, batch ]
          exporters: [ otlphttp/logs ]
          # exporters: [ otlphttp/logs, debug/logs ]  # Uncomment this line to enable debug logging
