name: Acceptance Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  acceptance-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Build
        run: ./gradlew clean check shadowJar

      - name: Check out oats
        uses: actions/checkout@v4
        with:
          repository: grafana/oats
          ref: b4c9c7738576c10bdaf8541eede4a65ed0ee95af
          path: oats
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: oats/go.sum
      - name: Run acceptance tests
        run: .github/scripts/run-acceptance-tests.sh
      - name: upload log file
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: OATS logs
          path: oats/yaml/build/**/*.log
